### ISSUE TITLE
Cannot run project?

### ISSUE THREAD

**Issue by bobi33** [VJAI/JustBlog#2]
Hi, it looks like I cannot run the solution. I get the error: "The type or namespace name "global_asax" does not exist in the namespace "ASP" (you are missing an assembly reference?).

Is there a fix for this?

**Comment by VJAI** [comment]
I've never seen this issue before. Very strange! Did you look at this thread http://stackoverflow.com/questions/28513532/asp-global-asax-does-not-exist-in-the-namespace-asp? Let me know still you've problems.

**Comment by bobi33** [comment]
Thanks. I will take a look at that post. I am essentially trying to use the blog engine in an existing website, but before I am integrating it, I am trying to run the solution and getting the error.

On Feb 9, 2017, at 23:21, Vijaya Anand <notifications@github.com<mailto:notifications@github.com>> wrote:


I've never seen this issue before. Very strange! Did you look at this thread http://stackoverflow.com/questions/28513532/asp-global-asax-does-not-exist-in-the-namespace-asp? Let me know still you've problems.

**Comment by VJAI** [comment]
Do you able to run other ASP.NET MVC 4 applications in your machine? Can you also provide what Windows OS you are using? I'll try tonight and will provide useful info about this issue.

**Comment by bobi33** [comment]
Yes, I am able to run other asp web apps on my machine. I am using VS Community 2015 on a Windows 10 with anniversary update OS.

On Feb 10, 2017, at 03:56, Vijaya Anand <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you able to run other ASP.NET<http://ASP.NET> MVC 4 applications in your machine? Can you also provide what Windows OS you are using? I'll try tonight and will provide useful info about this issue.

**Comment by bobi33** [comment]
I just repaired VS, and am now getting: "SqlException was unhandled by user code: An exception of type 'System.Data.SqlClient.SqlException' occurred in NHibernate.dll but was not handled in user code

Additional information: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)".

Microsoft Edge loads a page indicated that there was a server error.

**Comment by VJAI** [comment]
Please go through this link http://prideparrot.com/downloads/justblog. It'll help you how to configure the application.

**Comment by bobi33** [comment]
Thanks, it seems that the JustBlog.sqp script completes with errors, but the ELMAH-1.2-db-SQLServer.sql completes without errors...am I doing something wrong here? I've created a MS Sql Server with my hosting provider; gave it a unique name, and added a user name and password...

**Comment by bobi33** [comment]
I figured the above out, by creating a database called JustBlog, rather than using a unique name I thought of; however, I am still getting:

"SqlException was unhandled by user code: An exception of type 'System.Data.SqlClient.SqlException' occurred in NHibernate.dll but was not handled in user code

Additional information: The target principal name is incorrect.  Cannot generate SSPI context"...

**Comment by bobi33** [comment]
I figured that out too. What happened was the web.config file did not have the correct connectionstrings for the database.
